package com.amp.reports;

/**
 * Structured narrative sections generated by AI for inclusion in reports.
 */
public record NarrativeSections(
        String executiveSummary,
        String campaignHighlights,
        String areasForImprovement,
        String actionsTaken,
        String recommendations
) {

    /** Convenience factory for a single executive summary (manual edit). */
    public static NarrativeSections ofSummary(String summary) {
        return new NarrativeSections(summary, null, null, null, null);
    }

    /** Returns true if at least one section has content. */
    public boolean hasContent() {
        return hasText(executiveSummary)
                || hasText(campaignHighlights)
                || hasText(areasForImprovement)
                || hasText(actionsTaken)
                || hasText(recommendations);
    }

    private static boolean hasText(String s) {
        return s != null && !s.isBlank();
    }
}
